name: Conan-ci

'on':
    pull_request:
    push:
        branches:
          - master
          - dev*
          - feature/**

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
    MSVC:
        runs-on: windows-2019
        name: windows-2019
        strategy:
            fail-fast: false
            matrix: 
               os: [windows-2019]

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - uses: actions/setup-python@v4
            with:
                python-version: '3.10' 
                cache: 'pip' # caching pip dependencies
          - name: Conan detect
            run: |
                pip install "conan>=1.51.0,<2.0.0"
                conan profile new --detect default

          - name: Run conan
            run: |
                conan create . --build=missing -pr:b=default

    GCC:
        runs-on: ubuntu-22.04
        name: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix: 
               os: [ubuntu-22.04]

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          
          - name: Install packages
            run: |
                sudo apt-get update
                sudo apt-get install -y gcc g++ cmake wget git python3 python3-pip libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev uuid-dev libxcb-util-dev libxcb-util0-dev libxcb-cursor-dev
                pip install ninja "conan>=1.51.0,<2.0.0" 
                conan profile new --detect default
                conan profile update settings.compiler.libcxx=libstdc++11 default
              
          - name: Run conan
            run: |
                conan create . --build=missing -pr:b=default

